# This is a basic workflow to help you get started with Actions

name: Do a quarterly data load


# Controls when the action will run. 
on:
  schedule:
    - cron:  '15 2 1 */3 *'    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  etl:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: clear cache
        uses: michcio1234/heroku-run@0.1.1
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_ACCOUNT }}
          heroku_app_name: ${{ secrets.HEROKU_APP }}
          command: make quarterly
