# This is a basic workflow to help you get started with Actions
name: Run lobbyist scrape

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [lobbyist.xlsx, lobbyist_employer.xlsx]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: setup requirementss
        run: pip install -r requirements.txt
      - name: scrape lobbyist data
        run: make data/processed/${{ matrix.target }}
      - name: upload to s3
        env:
          S3BUCKET: ${{ secrets.S3BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp data/processed/${{ matrix.target }} $S3BUCKET --acl public-read
